/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GamesLevel;

import Score.MyText;
import Score.WriteAndRead_Level1;
import static Score.WriteAndRead_Level1.arrayList;
import Score.WriteAndRead_Level2;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Stack;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author Vipul
 */
public class Level_2 extends javax.swing.JFrame implements Runnable {

    private int boy_x;
    private int boy_y;
    private int Tresure1_X;
    private int Tresure2_X;
    private int Tresure3_X;

    private int Tresure1_Y;
    private int Tresure2_Y;
    private int Tresure3_Y;

    //Range Between Tresure and Boy
    private int Tresure1_boy_X;
    private int Tresure1_boy_Y;

    private int Tresure2_boy_X;
    private int Tresure2_boy_Y;

    private int Tresure3_boy_X;
    private int Tresure3_boy_Y;

    // boy data store
    private final ArrayList<Integer> x_array_boy = new ArrayList<>();
    private final ArrayList<Integer> y_array_boy = new ArrayList<>();

    private static final Stack<ArrayList> X_cordinateDB_boy = new Stack<>();
    private static final Stack<ArrayList> Y_cordinateDB_boy = new Stack<>();

    // Tresure1 data store
    private final ArrayList<Integer> x_array_tresure1 = new ArrayList<>();
    private final ArrayList<Integer> y_array_tresure1 = new ArrayList<>();

    private static final Stack<ArrayList> X_cordinateDB_tresure1 = new Stack<>();
    private static final Stack<ArrayList> Y_cordinateDB_tresure1 = new Stack<>();

    //Tresure2 data store
    private final ArrayList<Integer> x_array_tresure2 = new ArrayList<>();
    private final ArrayList<Integer> y_array_tresure2 = new ArrayList<>();

    private static final Stack<ArrayList> X_cordinateDB_tresure2 = new Stack<>();
    private static final Stack<ArrayList> Y_cordinateDB_tresure2 = new Stack<>();

    //Tresure3 data store
    private final ArrayList<Integer> x_array_tresure3 = new ArrayList<>();
    private final ArrayList<Integer> y_array_tresure3 = new ArrayList<>();

    private static final Stack<ArrayList> X_cordinateDB_tresure3 = new Stack<>();
    private static final Stack<ArrayList> Y_cordinateDB_tresure3 = new Stack<>();

    //other things
    private int boy_count = 0;
    private int tresure_count1 = 0;
    private int tresure_count2 = 0;
    private int tresure_count3 = 0;

    private int boy_x_undo;
    private int boy_y_undo;
    private int Tresure1_x_undo;
    private int Tresure1_y_undo;
    private int Tresure2_x_undo;
    private int Tresure2_y_undo;
    private int Tresure3_x_undo;
    private int Tresure3_y_undo;

    private static Clip clip;

    // Time
    private final int i = 0;
    private int startMinutes = 0;
    private final String maxtime;
    private String maxtime1;
    private int j = 0;

    /**
     * Creates new form Level_2
     */
    public Level_2() {
        initComponents();
        PlayMusic();
        time();
        Box_1.setVisible(false);
        Box_2.setVisible(false);
        Box_3.setVisible(false);
        setLocation(600, 100);
        if (new WriteAndRead_Level2().readObject() == null) {
            jLabel2_Moves.setText("");
            maxtime = "00:00";
        } else {

            jLabel2_Moves.setText(WriteAndRead_Level2.txt.toString());
            maxtime = WriteAndRead_Level2.txt.toString();

        }
        int x = jLabel2.getLocation().x;
        int y = jLabel2.getLocation().y;

        System.out.println("X" + x);
        System.out.println("Y" + y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1_Tresure1 = new javax.swing.JButton();
        jButton2_Tresure2 = new javax.swing.JButton();
        jButton3_Tresure3 = new javax.swing.JButton();
        jButton1_boy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Box_1 = new javax.swing.JButton();
        Box_2 = new javax.swing.JButton();
        Box_3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1_undo1 = new javax.swing.JButton();
        jButton1_sound = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2_Moves = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2_Moves1 = new javax.swing.JLabel();
        jLabel4_Time = new javax.swing.JLabel();
        jLabel4_Time1 = new javax.swing.JLabel();
        jLabel6_X = new javax.swing.JLabel();
        jLabel5_Y = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8_x = new javax.swing.JLabel();
        jLabel9_y = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jButton1_Tresure1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon1_3.jpg"))); // NOI18N
        jButton1_Tresure1.setText("1");
        jButton1_Tresure1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Tresure1ActionPerformed(evt);
            }
        });
        jButton1_Tresure1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1_Tresure1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1_Tresure1);
        jButton1_Tresure1.setBounds(410, 610, 70, 60);

        jButton2_Tresure2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon1_3.jpg"))); // NOI18N
        jButton2_Tresure2.setText("2");
        jButton2_Tresure2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_Tresure2ActionPerformed(evt);
            }
        });
        jButton2_Tresure2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2_Tresure2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton2_Tresure2);
        jButton2_Tresure2.setBounds(340, 610, 70, 60);

        jButton3_Tresure3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon1_3.jpg"))); // NOI18N
        jButton3_Tresure3.setText("3");
        jButton3_Tresure3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_Tresure3ActionPerformed(evt);
            }
        });
        jButton3_Tresure3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3_Tresure3KeyPressed(evt);
            }
        });
        jPanel1.add(jButton3_Tresure3);
        jButton3_Tresure3.setBounds(270, 610, 70, 60);

        jButton1_boy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon1.png"))); // NOI18N
        jButton1_boy.setText("BOY");
        jButton1_boy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_boyActionPerformed(evt);
            }
        });
        jButton1_boy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1_boyKeyPressed(evt);
            }
        });
        jPanel1.add(jButton1_boy);
        jButton1_boy.setBounds(380, 90, 70, 60);

        jLabel2.setBackground(new java.awt.Color(255, 0, 51));
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2_2.png"))); // NOI18N
        jLabel2.setText("        3");
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 370, 70, 60);

        jLabel3.setBackground(new java.awt.Color(0, 0, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2_2.png"))); // NOI18N
        jLabel3.setText("        1 ");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 250, 70, 60);

        jLabel4.setBackground(new java.awt.Color(51, 51, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2_2.png"))); // NOI18N
        jLabel4.setText("        2");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 310, 70, 60);

        Box_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2_1.png"))); // NOI18N
        Box_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_1ActionPerformed(evt);
            }
        });
        jPanel1.add(Box_1);
        Box_1.setBounds(40, 560, 80, 60);

        Box_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2_1.png"))); // NOI18N
        jPanel1.add(Box_2);
        Box_2.setBounds(40, 630, 80, 60);

        Box_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2_1.png"))); // NOI18N
        jPanel1.add(Box_3);
        Box_3.setBounds(40, 700, 80, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maps/Level-2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(6, 6, 727, 788);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 800));

        jButton1_undo1.setText("Undo");
        jButton1_undo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_undo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_undo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 850, 110, 40));

        jButton1_sound.setText("Pause");
        jButton1_sound.setMaximumSize(new java.awt.Dimension(59, 32));
        jButton1_sound.setMinimumSize(new java.awt.Dimension(59, 32));
        jButton1_sound.setPreferredSize(new java.awt.Dimension(59, 32));
        jButton1_sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_soundActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_sound, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 850, 100, 40));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("  Best Score");
        jLabel9.setPreferredSize(new java.awt.Dimension(59, 32));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 850, 110, 40));

        jLabel2_Moves.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jLabel2_Moves.setText("  Score");
        jLabel2_Moves.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel2_Moves, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 850, 100, 40));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("   Moves");
        jLabel8.setPreferredSize(new java.awt.Dimension(59, 32));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 850, 90, 40));

        jLabel2_Moves1.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jLabel2_Moves1.setText(" Moves");
        jLabel2_Moves1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel2_Moves1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 850, 80, 40));

        jLabel4_Time.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4_Time.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4_Time.setText("  Time");
        jLabel4_Time.setPreferredSize(new java.awt.Dimension(59, 32));
        getContentPane().add(jLabel4_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 850, 70, 40));

        jLabel4_Time1.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jLabel4_Time1.setText(" Time");
        jLabel4_Time1.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel4_Time1.setPreferredSize(new java.awt.Dimension(59, 32));
        getContentPane().add(jLabel4_Time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 850, 70, 40));

        jLabel6_X.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6_X.setText("   X");
        getContentPane().add(jLabel6_X, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 800, 70, -1));

        jLabel5_Y.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5_Y.setText("  Y");
        getContentPane().add(jLabel5_Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 800, 70, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Target Location");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 800, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Tresure Location");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 800, -1, -1));

        jLabel8_x.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8_x.setText("   X");
        getContentPane().add(jLabel8_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 800, 60, -1));

        jLabel9_y.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9_y.setText("  Y");
        getContentPane().add(jLabel9_y, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 800, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_Tresure1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1_Tresure1KeyPressed

    }//GEN-LAST:event_jButton1_Tresure1KeyPressed

    private void jButton1_Tresure1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Tresure1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_Tresure1ActionPerformed

    private void jButton1_boyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_boyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_boyActionPerformed

    private void jButton1_boyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1_boyKeyPressed
        boy_x = jButton1_boy.getLocation().x;
        boy_y = jButton1_boy.getLocation().y;
        Tresure1_X = jButton1_Tresure1.getLocation().x;
        Tresure2_X = jButton2_Tresure2.getLocation().x;
        Tresure3_X = jButton3_Tresure3.getLocation().x;

        Tresure1_Y = jButton1_Tresure1.getLocation().y;
        Tresure2_Y = jButton2_Tresure2.getLocation().y;
        Tresure3_Y = jButton3_Tresure3.getLocation().y;

        goBoy(
                evt, boy_x, boy_y, Tresure1_X, Tresure2_X, Tresure3_X, Tresure1_Y,
                Tresure2_Y, Tresure3_Y
        );
        if (Tresure1_X == 290 && Tresure1_Y == 250) {
            tresure01(Tresure1_X, Tresure1_Y);
        }
        if (Tresure2_X == 360 && Tresure2_Y == 310) {
            tresure02(Tresure2_X, Tresure2_Y);
        }
        if (Tresure3_X == 290 && Tresure3_Y == 370) {
            tresure03(Tresure3_X, Tresure3_Y);
        }
    }//GEN-LAST:event_jButton1_boyKeyPressed

    private void jButton2_Tresure2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_Tresure2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2_Tresure2ActionPerformed

    private void jButton2_Tresure2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2_Tresure2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2_Tresure2KeyPressed

    private void jButton3_Tresure3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_Tresure3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3_Tresure3ActionPerformed

    private void jButton3_Tresure3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3_Tresure3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3_Tresure3KeyPressed

    private void jButton1_undo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_undo1ActionPerformed
        undo_boy();
        undo_Tresure1();
        undo_Tresure2();
        undo_Tresure3();

    }//GEN-LAST:event_jButton1_undo1ActionPerformed

    private void jButton1_soundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_soundActionPerformed

        if (jButton1_sound.getText().equals("Play")) {

            PlayMusic();

            jButton1_sound.setText("Pause");
        } else {
            PauseMusic();
            jButton1_sound.setText("Play");

        }
    }//GEN-LAST:event_jButton1_soundActionPerformed

    private void Box_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Box_1;
    private javax.swing.JButton Box_2;
    private javax.swing.JButton Box_3;
    private javax.swing.JButton jButton1_Tresure1;
    private javax.swing.JButton jButton1_boy;
    private javax.swing.JButton jButton1_sound;
    private javax.swing.JButton jButton1_undo1;
    private javax.swing.JButton jButton2_Tresure2;
    private javax.swing.JButton jButton3_Tresure3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_Moves;
    private javax.swing.JLabel jLabel2_Moves1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4_Time;
    private javax.swing.JLabel jLabel4_Time1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5_Y;
    private javax.swing.JLabel jLabel6_X;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel8_x;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel9_y;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void goBoy(KeyEvent key, int boy_x, int boy_y, int Tresure1_x, int Tresure2_x,
            int Tresure3_x, int Tresure1_y, int Tresure2_y, int Tresure3_y) {

        this.boy_x = boy_x;
        this.boy_y = boy_y;
        this.Tresure1_X = Tresure1_x;
        this.Tresure2_X = Tresure2_x;
        this.Tresure3_X = Tresure3_x;
        this.Tresure1_Y = Tresure1_y;
        this.Tresure2_Y = Tresure2_y;
        this.Tresure3_Y = Tresure3_y;

        Tresure1_boy_X = Tresure1_X - boy_x;
        Tresure1_boy_Y = Tresure1_Y - boy_y;

        Tresure2_boy_X = Tresure2_X - boy_x;
        Tresure2_boy_Y = Tresure2_Y - boy_y;

        Tresure3_boy_X = Tresure3_X - boy_x;
        Tresure3_boy_Y = Tresure3_Y - boy_y;

        int keys = key.getKeyCode();

        switch (keys) {
            case KeyEvent.VK_UP:
                if ((boy_y == 70) || (boy_x <= 210 && boy_y == 265)
                        && (boy_x >= 75 && boy_y == 265)) {

                } else {

                    if (Tresure1_boy_X == 0 && Tresure1_boy_Y == -60) {
                        jLabel6_X.setText("" + 290);
                        jLabel5_Y.setText("" + 250);
                        if ((boy_y == 130) || (boy_x <= 215 && boy_y == 325)
                                && (boy_x >= 75 && boy_y == 325)
                                || (boy_x == 550 && boy_y == 455)) {

                        } else {
                            jButton1_boy.setLocation(boy_x, boy_y - 5);
                            jButton1_Tresure1.setLocation(Tresure1_x, Tresure1_y - 5);

                            int X = jButton1_Tresure1.getLocation().x;
                            int Y = jButton1_Tresure1.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count1++;

                            x_array_tresure1.add(Tresure1_X);
                            X_cordinateDB_tresure1.push(x_array_tresure1);
                            y_array_tresure1.add(Tresure1_Y);
                            Y_cordinateDB_tresure1.push(y_array_tresure1);
                        }

                    }
                    if (Tresure2_boy_X == 0 && Tresure2_boy_Y == -60) {
                        jLabel6_X.setText("" + 360);
                        jLabel5_Y.setText("" + 310);
                        if ((boy_y == 130) || (boy_x <= 215 && boy_y == 325)
                                && (boy_x >= 75 && boy_y == 325)
                                || (boy_x == 550 && boy_y == 455)) {

                        } else {
                            jButton1_boy.setLocation(boy_x, boy_y - 5);
                            jButton2_Tresure2.setLocation(Tresure2_x, Tresure2_y - 5);
                            int X = jButton2_Tresure2.getLocation().x;
                            int Y = jButton2_Tresure2.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count2++;

                            x_array_tresure2.add(Tresure2_X);
                            X_cordinateDB_tresure2.push(x_array_tresure2);
                            y_array_tresure2.add(Tresure2_Y);
                            Y_cordinateDB_tresure2.push(y_array_tresure2);
                        }
                    }
                    if (Tresure3_boy_X == 0 && Tresure3_boy_Y == -60) {
                        jLabel6_X.setText("" + 290);
                        jLabel5_Y.setText("" + 372);
                        if ((boy_y == 130) || (boy_x <= 215 && boy_y == 325)
                                && (boy_x >= 75 && boy_y == 325)
                                || (boy_x == 550 && boy_y == 455)) {

                        } else {
                            jButton1_boy.setLocation(boy_x, boy_y - 5);
                            jButton3_Tresure3.setLocation(Tresure3_x, Tresure3_y - 5);
                            int X = jButton3_Tresure3.getLocation().x;
                            int Y = jButton3_Tresure3.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);

                            tresure_count3++;

                            x_array_tresure3.add(Tresure3_X);
                            X_cordinateDB_tresure3.push(x_array_tresure3);
                            y_array_tresure3.add(Tresure3_Y);
                            Y_cordinateDB_tresure3.push(y_array_tresure3);
                        }
                    } else {
                        jButton1_boy.setLocation(boy_x, boy_y - 5);
                        boy_count++;
                        x_array_boy.add(boy_x);
                        X_cordinateDB_boy.push(x_array_boy);
                        y_array_boy.add(boy_y);
                        Y_cordinateDB_boy.push(y_array_boy);
                    }
                }
                break;

            case KeyEvent.VK_DOWN:
                if ((boy_y == 680) || (boy_x <= 555 && boy_y == 560)
                        && (boy_x >= 535 && boy_y == 560)
                        || (boy_x <= 210 && boy_y == 355)
                        && (boy_x >= 75 && boy_y == 355)) {

                } else {

                    if (Tresure1_boy_X == 0 && Tresure1_boy_Y == 60) {
                        jLabel6_X.setText("" + 290);
                        jLabel5_Y.setText("" + 250);
                        if ((boy_y == 625) || (boy_x <= 550 && boy_y == 500)
                                && (boy_x >= 510 && boy_y == 500)
                                || (boy_x <= 205 && boy_y == 295)
                                && (boy_x >= 75 && boy_y == 295)) {

                        } else {

                            jButton1_boy.setLocation(boy_x, boy_y + 5);
                            jButton1_Tresure1.setLocation(Tresure1_x, Tresure1_y + 5);
                            tresure_count1++;
                            int X = jButton1_Tresure1.getLocation().x;
                            int Y = jButton1_Tresure1.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            x_array_tresure1.add(Tresure1_X);
                            X_cordinateDB_tresure1.push(x_array_tresure1);
                            y_array_tresure1.add(Tresure1_Y);
                            Y_cordinateDB_tresure1.push(y_array_tresure1);

                        }
                    }
                    if (Tresure2_boy_X == 0 && Tresure2_boy_Y == 60) {
                        jLabel6_X.setText("" + 360);
                        jLabel5_Y.setText("" + 310);
                        if ((boy_y == 625) || (boy_x <= 550 && boy_y == 500)
                                && (boy_x >= 510 && boy_y == 500)
                                || (boy_x <= 205 && boy_y == 295)
                                && (boy_x >= 75 && boy_y == 295)) {

                        } else {
                            jButton1_boy.setLocation(boy_x, boy_y + 5);
                            jButton2_Tresure2.setLocation(Tresure2_x, Tresure2_y + 5);
                            int X = jButton2_Tresure2.getLocation().x;
                            int Y = jButton2_Tresure2.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count2++;

                            x_array_tresure2.add(Tresure2_X);
                            X_cordinateDB_tresure2.push(x_array_tresure2);
                            y_array_tresure2.add(Tresure2_Y);
                            Y_cordinateDB_tresure2.push(y_array_tresure2);
                        }
                    }
                    if (Tresure3_boy_X == 0 && Tresure3_boy_Y == 60) {
                        jLabel6_X.setText("" + 290);
                        jLabel5_Y.setText("" + 372);
                        if ((boy_y == 625) || (boy_x <= 550 && boy_y == 500)
                                && (boy_x >= 510 && boy_y == 500)
                                || (boy_x <= 205 && boy_y == 295)
                                && (boy_x >= 75 && boy_y == 295)) {

                        } else {
                            jButton1_boy.setLocation(boy_x, boy_y + 5);
                            jButton3_Tresure3.setLocation(Tresure3_x, Tresure3_y + 5);
                            int X = jButton3_Tresure3.getLocation().x;
                            int Y = jButton3_Tresure3.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count3++;

                            x_array_tresure3.add(Tresure3_X);
                            X_cordinateDB_tresure3.push(x_array_tresure3);
                            y_array_tresure3.add(Tresure3_Y);
                            Y_cordinateDB_tresure3.push(y_array_tresure3);
                        }
                    } else {
                        jButton1_boy.setLocation(boy_x, boy_y + 5);
                        boy_count++;
                        x_array_boy.add(boy_x);
                        X_cordinateDB_boy.push(x_array_boy);
                        y_array_boy.add(boy_y);
                        Y_cordinateDB_boy.push(y_array_boy);
                    }
                }
                break;

            case KeyEvent.VK_LEFT:
                if ((boy_x == 75) || (boy_x == 275 && boy_y <= 210)
                        && (boy_x == 275 && boy_y >= 75)
                        || (boy_x == 270 && boy_y >= 410)
                        && boy_x == 270 && boy_y <= 680) {

                } else {

                    if (Tresure1_boy_X == -70 && Tresure1_boy_Y == 0) {
                        jLabel6_X.setText("" + 290);
                        jLabel5_Y.setText("" + 250);
                        if ((boy_x == 145) || (boy_x == 340 && boy_y >= 405)
                                && (boy_x == 340 && boy_y <= 680)) {

                        } else {
                            jButton1_boy.setLocation(boy_x - 5, boy_y);
                            jButton1_Tresure1.setLocation(Tresure1_x - 5, Tresure1_y);
                            int X = jButton1_Tresure1.getLocation().x;
                            int Y = jButton1_Tresure1.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count1++;

                            x_array_tresure1.add(Tresure1_X);
                            X_cordinateDB_tresure1.push(x_array_tresure1);
                            y_array_tresure1.add(Tresure1_Y);
                            Y_cordinateDB_tresure1.push(y_array_tresure1);
                        }
                    }
                    if (Tresure2_boy_X == -70 && Tresure2_boy_Y == 0) {
                        jLabel6_X.setText("" + 360);
                        jLabel5_Y.setText("" + 310);
                        if ((boy_x == 145) || (boy_x == 340 && boy_y >= 405)
                                && (boy_x == 340 && boy_y <= 680)) {

                        } else {
                            jButton1_boy.setLocation(boy_x - 5, boy_y);
                            jButton2_Tresure2.setLocation(Tresure2_x - 5, Tresure2_y);
                            int X = jButton2_Tresure2.getLocation().x;
                            int Y = jButton2_Tresure2.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count2++;

                            x_array_tresure2.add(Tresure2_X);
                            X_cordinateDB_tresure2.push(x_array_tresure2);
                            y_array_tresure2.add(Tresure2_Y);
                            Y_cordinateDB_tresure2.push(y_array_tresure2);
                        }
                    }
                    if (Tresure3_boy_X == -70 && Tresure3_boy_Y == 0) {
                        jLabel6_X.setText("" + 290);
                        jLabel5_Y.setText("" + 372);
                        if ((boy_x == 145) || (boy_x == 340 && boy_y >= 405)
                                && (boy_x == 340 && boy_y <= 680)) {

                        } else {
                            jButton1_boy.setLocation(boy_x - 5, boy_y);
                            jButton3_Tresure3.setLocation(Tresure3_x - 5, Tresure3_y);
                            int X = jButton3_Tresure3.getLocation().x;
                            int Y = jButton3_Tresure3.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count3++;

                            x_array_tresure3.add(Tresure3_X);
                            X_cordinateDB_tresure3.push(x_array_tresure3);
                            y_array_tresure3.add(Tresure3_Y);
                            Y_cordinateDB_tresure3.push(y_array_tresure3);
                        }
                    } else {

                        jButton1_boy.setLocation(boy_x - 5, boy_y);
                        boy_count++;
                        x_array_boy.add(boy_x);
                        X_cordinateDB_boy.push(x_array_boy);
                        y_array_boy.add(boy_y);
                        Y_cordinateDB_boy.push(y_array_boy);
                    }

                }
                break;

            case KeyEvent.VK_RIGHT:
                if ((boy_x == 550) || (boy_x == 530 && boy_y == 345)
                        && (boy_x <= 530 && boy_y >= 75)
                        || (boy_x == 490 && boy_y >= 620)
                        && (boy_x == 490 && boy_y <= 680)) {

                } else {

                    if (Tresure1_boy_X == 70 && Tresure1_boy_Y == 0) {
                        jLabel6_X.setText("" + 290);
                        jLabel5_Y.setText("" + 250);
                        if ((boy_x == 480) || (boy_x == 465 && boy_y <= 320)
                                && (boy_x == 465 && boy_y >= 70)
                                || (boy_x == 420 && boy_y >= 620)
                                && (boy_x == 420 && boy_y <= 680)) {

                        } else {
                            jButton1_boy.setLocation(boy_x + 5, boy_y);
                            jButton1_Tresure1.setLocation(Tresure1_x + 5, Tresure1_y);
                            int X = jButton1_Tresure1.getLocation().x;
                            int Y = jButton1_Tresure1.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count1++;

                            x_array_tresure1.add(Tresure1_X);
                            X_cordinateDB_tresure1.push(x_array_tresure1);
                            y_array_tresure1.add(Tresure1_Y);
                            Y_cordinateDB_tresure1.push(y_array_tresure1);
                        }

                    }
                    if (Tresure2_boy_X == 70 && Tresure2_boy_Y == 0) {
                        jLabel6_X.setText("" + 360);
                        jLabel5_Y.setText("" + 310);
                        if ((boy_x == 480) || (boy_x == 465 && boy_y <= 320)
                                && (boy_x == 465 && boy_y >= 70)
                                || (boy_x == 420 && boy_y >= 620)
                                && (boy_x == 420 && boy_y <= 680)) {

                        } else {
                            jButton1_boy.setLocation(boy_x + 5, boy_y);
                            jButton2_Tresure2.setLocation(Tresure2_x + 5, Tresure2_y);
                            int X = jButton2_Tresure2.getLocation().x;
                            int Y = jButton2_Tresure2.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count2++;

                            x_array_tresure2.add(Tresure2_X);
                            X_cordinateDB_tresure2.push(x_array_tresure2);
                            y_array_tresure2.add(Tresure2_Y);
                            Y_cordinateDB_tresure2.push(y_array_tresure2);
                        }
                    }
                    if (Tresure3_boy_X == 70 && Tresure3_boy_Y == 0) {
                        jLabel6_X.setText("" + 290);
                        jLabel5_Y.setText("" + 372);
                        if ((boy_x == 480) || (boy_x == 465 && boy_y <= 320)
                                && (boy_x == 465 && boy_y >= 70)
                                || (boy_x == 420 && boy_y >= 620)
                                && (boy_x == 420 && boy_y <= 680)) {

                        } else {
                            jButton1_boy.setLocation(boy_x + 5, boy_y);
                            jButton3_Tresure3.setLocation(Tresure3_x + 5, Tresure3_y);
                            int X = jButton3_Tresure3.getLocation().x;
                            int Y = jButton3_Tresure3.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count3++;

                            x_array_tresure3.add(Tresure3_X);
                            X_cordinateDB_tresure3.push(x_array_tresure3);
                            y_array_tresure3.add(Tresure3_Y);
                            Y_cordinateDB_tresure3.push(y_array_tresure3);
                        }
                    } else {
                        jButton1_boy.setLocation(boy_x + 5, boy_y);
                        boy_count++;
                        x_array_boy.add(boy_x);
                        X_cordinateDB_boy.push(x_array_boy);
                        y_array_boy.add(boy_y);
                        Y_cordinateDB_boy.push(y_array_boy);
                    }
                }
                break;

            default:
                System.out.println("Invalid");
        }

    }

    private void tresure01(int x2, int y2) {

        if ((x2 == 290 && y2 == 250)) {

            jButton1_Tresure1.setVisible(false);
            jLabel3.setVisible(false);
            Box_1.setVisible(true);

            j++;

        }
    }

    private void tresure02(int x2, int y2) {

        if ((x2 == 360 && y2 == 310)) {

            jButton2_Tresure2.setVisible(false);
            jLabel4.setVisible(false);
            Box_2.setVisible(true);

            j++;

        }
    }

    private void tresure03(int x2, int y2) {

        if ((x2 == 290 && y2 == 370)) {

            jButton3_Tresure3.setVisible(false);
            jLabel2.setVisible(false);
            Box_3.setVisible(true);

            j++;

        }
    }

    private void undo_boy() {

        if (boy_count > 0) {
            --boy_count;

            boy_x_undo = (int) X_cordinateDB_boy.pop().get(boy_count);
            boy_y_undo = (int) Y_cordinateDB_boy.pop().get(boy_count);

            jButton1_boy.setLocation(boy_x_undo, boy_y_undo);

        }

    }

    private void undo_Tresure1() {
        if (tresure_count1 > 0) {

            --tresure_count1;

            Tresure1_x_undo = (int) X_cordinateDB_tresure1.pop().get(tresure_count1);
            Tresure1_y_undo = (int) Y_cordinateDB_tresure1.pop().get(tresure_count1);

            jButton1_Tresure1.setLocation(Tresure1_x_undo, Tresure1_y_undo);

        }
    }

    private void undo_Tresure2() {
        if (tresure_count2 > 0) {

            --tresure_count2;

            Tresure2_x_undo = (int) X_cordinateDB_tresure2.pop().get(tresure_count2);
            Tresure2_y_undo = (int) Y_cordinateDB_tresure2.pop().get(tresure_count2);

            jButton2_Tresure2.setLocation(Tresure2_x_undo, Tresure2_y_undo);

        }
    }

    private void undo_Tresure3() {
        if (tresure_count3 > 0) {
            --tresure_count3;

            Tresure3_x_undo = (int) X_cordinateDB_tresure3.pop().get(tresure_count3);
            Tresure3_y_undo = (int) Y_cordinateDB_tresure3.pop().get(tresure_count3);

            jButton3_Tresure3.setLocation(Tresure3_x_undo, Tresure3_y_undo);

        }
    }

    private void PlayMusic() {
        try {
            File file = new File("music1.wav");
            if (file.exists()) {

                try (AudioInputStream audio2 = AudioSystem.getAudioInputStream(file)) {

                    try {

                        clip = AudioSystem.getClip();
                        clip.open(audio2);
                        clip.start();
                        clip.loop(Clip.LOOP_CONTINUOUSLY);

                    } catch (LineUnavailableException | IOException ex) {

                    }

                }
            }

        } catch (IOException | UnsupportedAudioFileException e) {

        }

    }

    private String PauseMusic() {
        try {
            File file = new File("music1.wav");
            if (file.exists()) {

                long microsecondLength = clip.getMicrosecondLength();
                clip.stop();
                clip.setMicrosecondPosition(microsecondLength);

                clip.flush();
                clip.close();

            }
        } catch (Exception e) {

        }

        return "";

    }

    private void time() {

        Thread thread = new Thread(this);

        thread.start();

    }

    @Override
    public void run() {
        int second = 0;
        try {

            int time = 0;

            while (startMinutes < 8) {
                for (time = 0; time <= 60; time++) {
                    Thread.sleep(1000);
                    JLabel j = new JLabel();

                    j.setText("0" + startMinutes + ":" + time);
                    jLabel4_Time1.setText(j.getText());

                    if (i == 60) {
                        startMinutes++;
                        j.setText(startMinutes + ":" + time);
                    }
                }

            }

            second++;

        } catch (Exception e) {
        }
    }

    private void BufferImage() {
        if (j == 3) {
            maxtime1 = jLabel4_Time1.getText();
            if (WriteAndRead_Level1.arrayList.isEmpty()) {
                MyText date1 = new MyText();
                date1.setText(maxtime);
                MyText date2 = new MyText();
                date2.setText(maxtime1);
                arrayList.add(date1);
                new WriteAndRead_Level1().writeObject(maxtime1, maxtime);

            } else {
                MyText date1 = new MyText();
                date1.setText(maxtime);
                MyText date2 = new MyText();
                date2.setText(maxtime1);
                arrayList.add(date1);
                new WriteAndRead_Level1().writeObject(maxtime, maxtime1);
            }

            Thread thread = new Thread(() -> {
                JFrame frame = new JFrame();
                frame.getContentPane();
                JPanel panel = new JPanel();

                ImageIcon icon = new ImageIcon();
                JLabel label = new JLabel(icon, JLabel.CENTER);

                ImageIcon buffericon = new ImageIcon("src/gif/loading.gif");
                Image img = buffericon.getImage();
                Image newimg = img.getScaledInstance(300, 250, Image.SCALE_DEFAULT);

                icon = new ImageIcon(newimg);
                label.setBounds(0, 0, 500, 500);

                label.setIcon(icon);

                panel.setLayout(null);
                panel.add(label);
                panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
                frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
                panel.setBackground(Color.white);
                frame.add(panel);
                frame.setUndecorated(true);
                frame.setSize(400, 400);
                frame.setVisible(true);
                frame.setBackground(new Color(0, 0, 0, 0));
                panel.setBackground(new Color(0, 0, 0, 0));
                label.setBackground(new Color(0, 0, 0, 0));
                frame.setLocation(750, 250);

                try {
                    Thread.sleep(2000);
                    frame.dispose();
                    dispose();
                    new Level_3().setVisible(true);
                    if (maxtime.isEmpty()) {
                        jLabel2_Moves.setText("0:0");
                    } else {

                    }
                } catch (Exception e) {
                }

                label.setSize(200, 200);
            });
            thread.start();
        }

    }

}
