/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GamesLevel;

import Score.MyText;
import Score.WriteAndRead_Level1;
import static Score.WriteAndRead_Level1.arrayList;
import com.alee.laf.WebLookAndFeel;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Stack;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author Vipul
 */
public class Level_1 extends javax.swing.JFrame implements Runnable {
// boy details

    private final ArrayList<Integer> x_array_boy = new ArrayList<>();
    private final ArrayList<Integer> y_array_boy = new ArrayList<>();

    private static final Stack<ArrayList> X_cordinateDB = new Stack<>();
    private static final Stack<ArrayList> Y_cordinateDB = new Stack<>();

    private int x = 0;
    private int y = 0;

    private int Boy_x;
    private int Boy_Y;
    private int Box_x;
    private int Box_y;
    private int Box1_x;
    private int Box1_y;
    private int Box2_x;
    private int Box2_y;
    private int i_boy = 0;
//box details
    private final ArrayList<Integer> x_array_box = new ArrayList<>();
    private final ArrayList<Integer> y_array_box = new ArrayList<>();

    private static final Stack<ArrayList> X_cordinateDB_box = new Stack<>();
    private static final Stack<ArrayList> Y_cordinateDB_box = new Stack<>();
//box1 details
    private final ArrayList<Integer> x_array_box1 = new ArrayList<>();
    private final ArrayList<Integer> y_array_box1 = new ArrayList<>();

    private static final Stack<ArrayList> X_cordinateDB_box1 = new Stack<>();
    private static final Stack<ArrayList> Y_cordinateDB_box1 = new Stack<>();

//box2 details 
    private final ArrayList<Integer> x_array_box2 = new ArrayList<>();
    private final ArrayList<Integer> y_array_box2 = new ArrayList<>();

    private static final Stack<ArrayList> X_cordinateDB_box2 = new Stack<>();
    private static final Stack<ArrayList> Y_cordinateDB_box2 = new Stack<>();

    private int i_box = 0;
    private int x1 = 0;
    private int y1 = 0;
    private int i_box1 = 0;
    private int x2 = 0;
    private int y2 = 0;
    private int i_box2 = 0;
    private int x3 = 0;
    private int y3 = 0;

    boolean flag = true;
    private static Clip clip;

    // Time
    private int startMinutes = 0;
    private int i = 0;
    private final String maxtime;
    private String maxtime1;

    //Tresure
    /**
     * Creates new form Moves
     */
    public Level_1() {

        initComponents();
        PlayMusic();
        time();
        jButton1_Tresure3.setSize(70, 60);
        jButton1_Tresure2.setSize(70, 60);
        jButton1_Tresure1.setSize(70, 60);
        Box_1.setVisible(false);
        Box_2.setVisible(false);
        Box_3.setVisible(false);
        jButton1_Tresure3.setVisible(false);
        jButton1_Tresure2.setVisible(true);
        jButton1_Tresure1.setVisible(false);

        setLocation(600, 100);
 //retreive score data from db(object Writing)
        if (new WriteAndRead_Level1().readObject() == null) {
            jLabel2_Moves.setText("");
            maxtime = "00:00";
        } else {

            jLabel2_Moves.setText(WriteAndRead_Level1.txt.toString());
            maxtime = WriteAndRead_Level1.txt.toString();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1_Boy = new javax.swing.JButton();
        jButton1_Tresure1 = new javax.swing.JButton();
        Box_2 = new javax.swing.JButton();
        Box_3 = new javax.swing.JButton();
        Box_1 = new javax.swing.JButton();
        jButton1_Tresure3 = new javax.swing.JButton();
        jButton1_Tresure2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1_undo1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2_Moves = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4_Time = new javax.swing.JLabel();
        jLabel4_Time1 = new javax.swing.JLabel();
        jLabel2_Moves1 = new javax.swing.JLabel();
        jButton1_sound = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5_Y = new javax.swing.JLabel();
        jLabel6_X = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8_x = new javax.swing.JLabel();
        jLabel9_y = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jButton1_Boy.setBackground(new java.awt.Color(255, 255, 255));
        jButton1_Boy.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_Boy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon1.png"))); // NOI18N
        jButton1_Boy.setText("Boy");
        jButton1_Boy.setBorder(null);
        jButton1_Boy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_BoyActionPerformed(evt);
            }
        });
        jButton1_Boy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1_BoyKeyPressed(evt);
            }
        });
        jPanel1.add(jButton1_Boy);
        jButton1_Boy.setBounds(130, 250, 70, 60);

        jButton1_Tresure1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1_Tresure1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_Tresure1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2.png"))); // NOI18N
        jButton1_Tresure1.setText("X");
        jButton1_Tresure1.setBorder(null);
        jButton1_Tresure1.setMaximumSize(new java.awt.Dimension(51, 32));
        jButton1_Tresure1.setMinimumSize(new java.awt.Dimension(51, 32));
        jButton1_Tresure1.setPreferredSize(new java.awt.Dimension(51, 32));
        jButton1_Tresure1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1_Tresure1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1_Tresure1);
        jButton1_Tresure1.setBounds(430, 280, 90, 60);

        Box_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2_1.png"))); // NOI18N
        jPanel1.add(Box_2);
        Box_2.setBounds(20, 650, 80, 60);

        Box_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2_1.png"))); // NOI18N
        jPanel1.add(Box_3);
        Box_3.setBounds(20, 710, 80, 60);

        Box_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2_1.png"))); // NOI18N
        jPanel1.add(Box_1);
        Box_1.setBounds(20, 590, 80, 60);

        jButton1_Tresure3.setBackground(new java.awt.Color(255, 255, 255));
        jButton1_Tresure3.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_Tresure3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2.png"))); // NOI18N
        jButton1_Tresure3.setText("X");
        jButton1_Tresure3.setBorder(null);
        jButton1_Tresure3.setMaximumSize(new java.awt.Dimension(51, 32));
        jButton1_Tresure3.setMinimumSize(new java.awt.Dimension(51, 32));
        jButton1_Tresure3.setPreferredSize(new java.awt.Dimension(51, 32));
        jButton1_Tresure3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1_Tresure3KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1_Tresure3);
        jButton1_Tresure3.setBounds(201, 250, 90, 60);

        jButton1_Tresure2.setBackground(new java.awt.Color(255, 255, 255));
        jButton1_Tresure2.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_Tresure2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2.png"))); // NOI18N
        jButton1_Tresure2.setText("X");
        jButton1_Tresure2.setBorder(null);
        jButton1_Tresure2.setMaximumSize(new java.awt.Dimension(51, 32));
        jButton1_Tresure2.setMinimumSize(new java.awt.Dimension(51, 32));
        jButton1_Tresure2.setPreferredSize(new java.awt.Dimension(51, 32));
        jButton1_Tresure2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1_Tresure2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1_Tresure2);
        jButton1_Tresure2.setBounds(320, 600, 90, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maps/Level-1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 820);

        jButton1_undo1.setText("Undo");
        jButton1_undo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_undo1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_undo1);
        jButton1_undo1.setBounds(10, 820, 100, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("   Moves");
        jLabel3.setPreferredSize(new java.awt.Dimension(59, 32));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 820, 70, 40);

        jLabel2_Moves.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jLabel2_Moves.setText("  Score");
        jLabel2_Moves.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel2_Moves);
        jLabel2_Moves.setBounds(370, 820, 80, 40);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("  Best Score");
        jLabel2.setPreferredSize(new java.awt.Dimension(59, 32));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 820, 90, 40);

        jLabel4_Time.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4_Time.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4_Time.setText("  Time");
        jLabel4_Time.setPreferredSize(new java.awt.Dimension(59, 32));
        jPanel1.add(jLabel4_Time);
        jLabel4_Time.setBounds(470, 820, 60, 40);

        jLabel4_Time1.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jLabel4_Time1.setText(" Time");
        jLabel4_Time1.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel4_Time1.setPreferredSize(new java.awt.Dimension(59, 32));
        jPanel1.add(jLabel4_Time1);
        jLabel4_Time1.setBounds(530, 820, 70, 40);

        jLabel2_Moves1.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jLabel2_Moves1.setText(" Moves");
        jLabel2_Moves1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel2_Moves1);
        jLabel2_Moves1.setBounds(180, 820, 80, 40);

        jButton1_sound.setText("Pause");
        jButton1_sound.setMaximumSize(new java.awt.Dimension(59, 32));
        jButton1_sound.setMinimumSize(new java.awt.Dimension(59, 32));
        jButton1_sound.setPreferredSize(new java.awt.Dimension(59, 32));
        jButton1_sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_soundActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_sound);
        jButton1_sound.setBounds(620, 820, 90, 40);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 730, 870));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Target Location");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 40));

        jLabel5_Y.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5_Y.setText("  Y");
        getContentPane().add(jLabel5_Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 50, 40));

        jLabel6_X.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6_X.setText("   X");
        getContentPane().add(jLabel6_X, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 50, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Tresure Location");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 200, 40));

        jLabel8_x.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8_x.setText("   X");
        getContentPane().add(jLabel8_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 70, 40));

        jLabel9_y.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9_y.setText("  Y");
        getContentPane().add(jLabel9_y, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 60, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_BoyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1_BoyKeyPressed
        int x = jButton1_Boy.getLocation().x;
        int y = jButton1_Boy.getLocation().y;
        int x1 = jButton1_Tresure3.getLocation().x;
        int y1 = jButton1_Tresure3.getLocation().y;
        int x2 = jButton1_Tresure2.getLocation().x;
        int y2 = jButton1_Tresure2.getLocation().y;
        int x3 = jButton1_Tresure1.getLocation().x;
        int y3 = jButton1_Tresure1.getLocation().y;

        goBoy(evt, x, y, x1, y1, x2, y2, x3, y3);

        if ((x2 == 335 && y2 == 530)) {
            tresure01(x2, y2);

        }

        if ((x3 == 420 && y3 == 380)) {

            tresure02(x3, y3);

        }
        if ((x1 == 206 && y1 == 330)) {
            tresure03(x1, y1);
            BufferImage();

        }


    }//GEN-LAST:event_jButton1_BoyKeyPressed

    private void jButton1_BoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_BoyActionPerformed

    }//GEN-LAST:event_jButton1_BoyActionPerformed

    private void jButton1_Tresure1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1_Tresure1KeyPressed


    }//GEN-LAST:event_jButton1_Tresure1KeyPressed

    private void jButton1_Tresure2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1_Tresure2KeyPressed

    }//GEN-LAST:event_jButton1_Tresure2KeyPressed

    private void jButton1_Tresure3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1_Tresure3KeyPressed

    }//GEN-LAST:event_jButton1_Tresure3KeyPressed

    private void jButton1_undo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_undo1ActionPerformed
        undo_boy();
        undo_box();
        undo_box1();
        undo_box2();

    }//GEN-LAST:event_jButton1_undo1ActionPerformed

    private void jButton1_soundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_soundActionPerformed

        if (jButton1_sound.getText().equals("Play")) {

            PlayMusic();

            jButton1_sound.setText("Pause");
        } else {
            PauseMusic();
            jButton1_sound.setText("Play");

        }

    }//GEN-LAST:event_jButton1_soundActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        try {
            WebLookAndFeel.install();

        } catch (Exception e) {
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Box_1;
    private javax.swing.JButton Box_2;
    private javax.swing.JButton Box_3;
    private javax.swing.JButton jButton1_Boy;
    private javax.swing.JButton jButton1_Tresure1;
    private javax.swing.JButton jButton1_Tresure2;
    private javax.swing.JButton jButton1_Tresure3;
    private javax.swing.JButton jButton1_sound;
    private javax.swing.JButton jButton1_undo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_Moves;
    private javax.swing.JLabel jLabel2_Moves1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4_Time;
    private javax.swing.JLabel jLabel4_Time1;
    private javax.swing.JLabel jLabel5_Y;
    private javax.swing.JLabel jLabel6_X;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8_x;
    private javax.swing.JLabel jLabel9_y;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

   // this content has every movements of sokoban 
    
    private void goBoy(KeyEvent evt, int x, int y, int x1, int y1, int x2, int y2, int x3, int y3) {

        Box_x = jButton1_Tresure3.getLocation().x;
        Boy_x = jButton1_Boy.getLocation().x;

        Box_y = jButton1_Tresure3.getLocation().y;
        Boy_Y = jButton1_Boy.getLocation().y;

        Box1_x = jButton1_Tresure1.getLocation().x;
        Box1_y = jButton1_Tresure1.getLocation().y;

        Box2_x = jButton1_Tresure2.getLocation().x;
        Box2_y = jButton1_Tresure2.getLocation().y;
        // i used this output variable for bind my player and tresure
        
        int output1 = Box_x - Boy_x;
        int output5 = Box1_x - Boy_x;
        int output6 = Box2_x - Boy_x;

        int output2 = Box_y - Boy_Y;
        int output3 = Box1_y - Boy_Y;
        int output4 = Box2_y - Boy_Y;

        int moveKey = evt.getKeyCode();
        
        // handling keys for moving playr and tresure
        switch (moveKey) {

            case KeyEvent.VK_UP:
                if ((output1 == 0 & output2 == -60) || (output1 == 1 & output2 == -60)) {
                    jLabel6_X.setText("" + 206);
                    jLabel5_Y.setText("" + 330);

                    i_boy++;
                    i_box++;
                    if ((y1 == 90) || (y1 == 410 && x1 == 586) || (y1 == 220 && x1 <= 211)) {

                    } else {

                        jButton1_Boy.setLocation(x, y - 5);

                        x_array_boy.add(x);
                        X_cordinateDB.push(x_array_boy);

                        y_array_boy.add(y);
                        Y_cordinateDB.push(y_array_boy);

                        jButton1_Tresure3.setLocation(x1, y1 - 5);

                        int x_tresure3 = jButton1_Tresure3.getLocation().x;
                        int y_tresure3 = jButton1_Tresure3.getLocation().y;

                        jLabel8_x.setText("" + x_tresure3);
                        jLabel9_y.setText("" + y_tresure3);

                        x_array_box.add(x1);
                        X_cordinateDB_box.push(x_array_box);

                        y_array_box.add(y1);
                        Y_cordinateDB_box.push(y_array_box);

                    }

                } else {

                    if ((x >= 80 && y == 220) && (x < 255 && y == 220)
                            || (x > 280 && y == 90) && (x < 515 && y == 90)
                            || (x == 585 && y < 420)) {

                    } else {

                        jButton1_Boy.setLocation(x, y - 5);

                        x_array_boy.add(x);
                        X_cordinateDB.push(x_array_boy);

                        y_array_boy.add(y);
                        Y_cordinateDB.push(y_array_boy);

                        if (output4 == -60 && output6 == 0) {
                            jLabel6_X.setText("" + 335);
                            jLabel5_Y.setText("" + 530);

                            if ((y2 == 90) || (y2 == 220 && x2 <= 210) || (y2 == 415 && x2 == 585)) {

                            } else {
                                i_boy++;
                                i_box1++;
                                jButton1_Tresure2.setLocation(x2, y2 - 5);
                                int x_tresure2 = jButton1_Tresure2.getLocation().x;
                                int y_tresure2 = jButton1_Tresure2.getLocation().y;

                                jLabel8_x.setText("" + x_tresure2);
                                jLabel9_y.setText("" + y_tresure2);

                                x_array_box1.add(x2);
                                X_cordinateDB_box1.push(x_array_box1);

                                y_array_box1.add(y2);
                                Y_cordinateDB_box1.push(y_array_box1);

                            }

                        }
                        if (output3 == -60 && output5 == 0) {
                            jLabel6_X.setText("" + 420);
                            jLabel5_Y.setText("" + 380);

                            if ((y3 == 580 && y3 == 410) || (y3 == 90) || (y3 == 220 && x3 <= 210)) {

                            } else {
                                i_boy++;
                                i_box2++;
                                jButton1_Tresure1.setLocation(x3, y3 - 5);
                                int x_tresure1 = jButton1_Tresure1.getLocation().x;
                                int y_tresure1 = jButton1_Tresure1.getLocation().y;

                                jLabel8_x.setText("" + x_tresure1);
                                jLabel9_y.setText("" + y_tresure1);

                                x_array_box2.add(x3);
                                X_cordinateDB_box2.push(x_array_box2);

                                y_array_box2.add(y3);
                                Y_cordinateDB_box2.push(y_array_box2);

                            }
                        }

                    }
                }
                break;

            case KeyEvent.VK_DOWN:

                if ((output1 == 0 & output2 == 60) || (output1 == 1 & output2 == 60)) {

                    jLabel6_X.setText("" + 206);
                    jLabel5_Y.setText("" + 330);

                    i_boy++;
                    i_box++;

                    if ((y1 == 670) || (y1 == 410 && x1 <= 141 || (y1 == 545 && x1 >= 516))) {

                    } else {

                        jButton1_Boy.setLocation(x, y + 5);

                        x_array_boy.add(x);
                        X_cordinateDB.push(x_array_boy);

                        y_array_boy.add(y);
                        Y_cordinateDB.push(y_array_boy);

                        jButton1_Tresure3.setLocation(x1, y1 + 5);
                        int x_tresure3 = jButton1_Tresure3.getLocation().x;
                        int y_tresure3 = jButton1_Tresure3.getLocation().y;

                        jLabel8_x.setText("" + x_tresure3);
                        jLabel9_y.setText("" + y_tresure3);

                        x_array_box.add(x1);
                        X_cordinateDB_box.push(x_array_box);

                        y_array_box.add(y1);
                        Y_cordinateDB_box.push(y_array_box);

                    }

                } else {

                    if ((x >= 70 && y == 410) && (x <= 185 && y == 410)
                            || (x > 480 && y == 545) && (x <= 585 && y == 545)
                            || ((x >= 205 && y == 670) && x <= 455 && y == 670)) {

                    } else {

                        jButton1_Boy.setLocation(x, y + 5);

                        x_array_boy.add(x);
                        X_cordinateDB.push(x_array_boy);

                        y_array_boy.add(y);
                        Y_cordinateDB.push(y_array_boy);

                        if (output4 == 60 & output6 == 0) {
                            jLabel6_X.setText("" + 335);
                            jLabel5_Y.setText("" + 530);

                            if ((y2 == 670) || (y2 == 410 && x2 <= 140) || (y2 == 545 && x2 >= 515)) {

                            } else {
                                i_boy++;
                                i_box1++;
                                jButton1_Tresure2.setLocation(x2, y2 + 5);
                                int x_tresure2 = jButton1_Tresure2.getLocation().x;
                                int y_tresure2 = jButton1_Tresure2.getLocation().y;

                                jLabel8_x.setText("" + x_tresure2);
                                jLabel9_y.setText("" + y_tresure2);

                                x_array_box1.add(x2);
                                X_cordinateDB_box1.push(x_array_box1);

                                y_array_box1.add(y2);
                                Y_cordinateDB_box1.push(y_array_box1);

                            }
                        }
                        if (output3 == 60 && output5 == 0) {
                            jLabel6_X.setText("" + 420);
                            jLabel5_Y.setText("" + 380);
                            if ((y3 == 670) || (y3 == 545 && x3 >= 515) || (y3 == 410 && x3 <= 140)) {

                            } else {
                                i_boy++;
                                i_box2++;
                                jButton1_Tresure1.setLocation(x3, y3 + 5);
                                int x_tresure1 = jButton1_Tresure1.getLocation().x;
                                int y_tresure1 = jButton1_Tresure1.getLocation().y;

                                jLabel8_x.setText("" + x_tresure1);
                                jLabel9_y.setText("" + y_tresure1);

                                x_array_box2.add(x3);
                                X_cordinateDB_box2.push(x_array_box2);

                                y_array_box2.add(y3);
                                Y_cordinateDB_box2.push(y_array_box2);

                            }
                        }
                    }
                }
                break;
            case KeyEvent.VK_RIGHT:

                if ((output1 == 71 & output2 == 0)) {
                    jLabel6_X.setText("" + 206);
                    jLabel5_Y.setText("" + 330);

                    i_boy++;
                    i_box++;

                    if ((x1 == 456 & y1 >= 600) || (x1 == 521 & y1 <= 350) || x1 == 586) {

                    } else {

                        jButton1_Boy.setLocation(x + 5, y);

                        x_array_boy.add(x);
                        X_cordinateDB.push(x_array_boy);

                        y_array_boy.add(y);
                        Y_cordinateDB.push(y_array_boy);

                        jButton1_Tresure3.setLocation(x1 + 5, y1);
                        int x_tresure3 = jButton1_Tresure3.getLocation().x;
                        int y_tresure3 = jButton1_Tresure3.getLocation().y;

                        jLabel8_x.setText("" + x_tresure3);
                        jLabel9_y.setText("" + y_tresure3);

                        x_array_box.add(x1);
                        X_cordinateDB_box.push(x_array_box);

                        y_array_box.add(y1);
                        Y_cordinateDB_box.push(y_array_box);

                   
                    }
                } else {

                    if ((x == 585 && y >= 410) || (x >= 455 && y == 670)
                            || (x == 455 && y > 575) || (x > 505 && y == 90)
                            || (x == 520 && y < 370)) {

                    } else {

                        jButton1_Boy.setLocation(x + 5, y);

                        x_array_boy.add(x);
                        X_cordinateDB.push(x_array_boy);

                        y_array_boy.add(y);
                        Y_cordinateDB.push(y_array_boy);

                        if (output6 == 70 & output4 == 0) {
                            jLabel6_X.setText("" + 335);
                            jLabel5_Y.setText("" + 530);

                            if ((x2 == 455 && y2 >= 595) || (x2 == 585) || (x2 == 520 && y2 <= 360)) {

                            } else {
                                i_boy++;
                                i_box1++;
                                jButton1_Tresure2.setLocation(x2 + 5, y2);
                                int x_tresure2 = jButton1_Tresure2.getLocation().x;
                                int y_tresure2 = jButton1_Tresure2.getLocation().y;

                                jLabel8_x.setText("" + x_tresure2);
                                jLabel9_y.setText("" + y_tresure2);

                                x_array_box1.add(x2);
                                X_cordinateDB_box1.push(x_array_box1);

                                y_array_box1.add(y2);
                                Y_cordinateDB_box1.push(y_array_box1);

                            }
                        }
                        if (output3 == 0 && output5 == 70) {
                            jLabel6_X.setText("" + 420);
                            jLabel5_Y.setText("" + 380);
                            if ((x3 == 520 && y3 <= 360) || (x3 == 585) || (x3 == 455 && y3 >= 595)) {

                            } else {
                                i_boy++;
                                i_box2++;

                                jButton1_Tresure1.setLocation(x3 + 5, y3);
                                int x_tresure1 = jButton1_Tresure1.getLocation().x;
                                int y_tresure1 = jButton1_Tresure1.getLocation().y;

                                jLabel8_x.setText("" + x_tresure1);
                                jLabel9_y.setText("" + y_tresure1);

                                x_array_box2.add(x3);
                                X_cordinateDB_box2.push(x_array_box2);

                                y_array_box2.add(y3);
                                Y_cordinateDB_box2.push(y_array_box2);

                            }
                        }

                    }
                }
                break;

            case KeyEvent.VK_LEFT:
                if (output1 == -74 & output2 == 0) {
                    jLabel6_X.setText("" + 206);
                    jLabel5_Y.setText("" + 330);

                    i_boy++;
                    i_box++;

                    if ((x1 == 86) || (x1 == 211 && y1 >= 465) || (x1 == 281 && y1 <= 165)) {

                    } else {

                        jButton1_Boy.setLocation(x - 5, y);

                        x_array_boy.add(x);
                        X_cordinateDB.push(x_array_boy);

                        y_array_boy.add(y);
                        Y_cordinateDB.push(y_array_boy);
                        jButton1_Tresure3.setLocation(x1 - 5, y1);
                        int x_tresure3 = jButton1_Tresure3.getLocation().x;
                        int y_tresure3 = jButton1_Tresure3.getLocation().y;

                        jLabel8_x.setText("" + x_tresure3);
                        jLabel9_y.setText("" + y_tresure3);

                        x_array_box.add(x1);
                        X_cordinateDB_box.push(x_array_box);

                        y_array_box.add(y1);
                        Y_cordinateDB_box.push(y_array_box);

                    }

                } else {

                    if ((x == 70 && y > 215) || (x == 70 && y > 410)
                            || (x > 445 && y == 670) || (x == 270 && y <= 155) || (x == 200 && y > 475)) {

                    } else {

                        jButton1_Boy.setLocation(x - 5, y);

                        x_array_boy.add(x);
                        X_cordinateDB.push(x_array_boy);

                        y_array_boy.add(y);
                        Y_cordinateDB.push(y_array_boy);

                        if (output6 == -70 && output4 == 0) {
                            jLabel6_X.setText("" + 335);
                            jLabel5_Y.setText("" + 530);

                            if ((x2 == 200 && y2 >= 475) || (x2 == 75) || (x2 == 270 && y2 <= 165)) {

                            } else {
                                i_boy++;
                                i_box1++;

                                jButton1_Tresure2.setLocation(x2 - 5, y2);
                                int x_tresure2 = jButton1_Tresure2.getLocation().x;
                                int y_tresure2 = jButton1_Tresure2.getLocation().y;

                                jLabel8_x.setText("" + x_tresure2);
                                jLabel9_y.setText("" + y_tresure2);

                                x_array_box1.add(x2);
                                X_cordinateDB_box1.push(x_array_box1);

                                y_array_box1.add(y2);
                                Y_cordinateDB_box1.push(y_array_box1);

                            }
                        }
                        if (output3 == 0 && output5 == -70) {
                            jLabel6_X.setText("" + 420);
                            jLabel5_Y.setText("" + 380);

                            if ((x3 == 70) || (x3 == 270 && y3 <= 165) || (x3 == 200 && y3 >= 465)) {

                            } else {
                                i_boy++;
                                i_box2++;

                                jButton1_Tresure1.setLocation(x3 - 5, y3);
                                int x_tresure1 = jButton1_Tresure1.getLocation().x;
                                int y_tresure1 = jButton1_Tresure1.getLocation().y;

                                jLabel8_x.setText("" + x_tresure1);
                                jLabel9_y.setText("" + y_tresure1);

                                x_array_box2.add(x3);
                                X_cordinateDB_box2.push(x_array_box2);

                                y_array_box2.add(y3);
                                Y_cordinateDB_box2.push(y_array_box2);

                            }
                        }

                    }
                }
                break;

            default:
                System.out.println("Invalid");
        }

    }
    // this is the place where my items located for hiding

    private void tresure01(int x2, int y2) {

        if ((x2 == 335 && y2 == 530)) {

            jButton1_Tresure2.setVisible(false);
            jButton1_Tresure1.setVisible(true);
            Box_1.setVisible(true);

            i++;
            flag = false;

        }

    }

    private void tresure02(int x3, int y3) {

        if ((x3 == 420 && y3 == 380)) {

            jButton1_Tresure1.setVisible(false);
            jButton1_Tresure3.setVisible(true);

            Box_2.setVisible(true);

            i++;

        }

    }

    private void tresure03(int x1, int y1) {

        if ((x1 == 206 && y1 == 330)) {

            jButton1_Tresure3.setVisible(false);
            Box_3.setVisible(true);

            i++;

        }

    }
    // this method for undo my player moves

    private void undo_boy() {

        if (i_boy > 0) {

            --i_boy;
            x = (int) X_cordinateDB.pop().get(i_boy);
            y = (int) Y_cordinateDB.pop().get(i_boy);

            jButton1_Boy.setLocation(x, y);

        }

    }
//this is a method for undo my player movements
    private void undo_box() {

        if (i_box > 0) {

            --i_box;
            x1 = (int) X_cordinateDB_box.pop().get(i_box);
            y1 = (int) Y_cordinateDB_box.pop().get(i_box);

            jButton1_Tresure3.setLocation(x1, y1);

        }

    }

    private void undo_box1() {

        if (i_box1 > 0) {

            --i_box1;
            x2 = (int) X_cordinateDB_box1.pop().get(i_box1);
            y2 = (int) Y_cordinateDB_box1.pop().get(i_box1);

            jButton1_Tresure2.setLocation(x2, y2);

        }

    }

    private void undo_box2() {

        if (i_box2 > 0) {

            --i_box2;
            x3 = (int) X_cordinateDB_box2.pop().get(i_box2);
            y3 = (int) Y_cordinateDB_box2.pop().get(i_box2);

            jButton1_Tresure1.setLocation(x3, y3);

        }

    }
// this is background music
    private void PlayMusic() {
        try {
            File file = new File("music1.wav");
            if (file.exists()) {

                try (AudioInputStream audio2 = AudioSystem.getAudioInputStream(file)) {

                    try {

                        clip = AudioSystem.getClip();
                        clip.open(audio2);
                        clip.start();
                        clip.loop(Clip.LOOP_CONTINUOUSLY);

                    } catch (LineUnavailableException | IOException ex) {

                    }

                }
            }

        } catch (IOException | UnsupportedAudioFileException e) {

        }

    }
//stop background music
    private String PauseMusic() {
        try {
            File file = new File("music1.wav");
            if (file.exists()) {

                long microsecondLength = clip.getMicrosecondLength();
                clip.stop();
                clip.setMicrosecondPosition(microsecondLength);

                clip.flush();
                clip.close();

            }
        } catch (Exception e) {

        }

        return "";

    }
    
    // time

    private void time() {

        Thread thread = new Thread(this);
        thread.start();

    }

    @Override
    public void run() {
        int second = 0;
        try {
            int i = 0;
            while (startMinutes < 3) {
                for (i = 0; i <= 60; i++) {
                    Thread.sleep(1000);
                    JLabel j = new JLabel();
                    j.setText("0" + startMinutes + ":" + i);
                    jLabel4_Time1.setText(j.getText());

                    if (i == 60) {
                        startMinutes++;
                        j.setText(startMinutes + ":" + i);
                    }
                }
            }
            second++;
        } catch (Exception e) {
        }
    }

    // bufferloading image
    private void BufferImage() {

        if (i == 3) {
            maxtime1 = jLabel4_Time1.getText();
            if (WriteAndRead_Level1.arrayList.isEmpty()) {
                MyText date1 = new MyText();
                date1.setText(maxtime);
                MyText date2 = new MyText();
                date2.setText(maxtime1);
                arrayList.add(date1);
                new WriteAndRead_Level1().writeObject(maxtime1, maxtime);

            } else {
                MyText date1 = new MyText();
                date1.setText(maxtime);
                MyText date2 = new MyText();
                date2.setText(maxtime1);
                arrayList.add(date1);
                new WriteAndRead_Level1().writeObject(maxtime, maxtime1);
            }

            Thread thread = new Thread(() -> {
                JFrame frame = new JFrame();
                frame.getContentPane();
                JPanel panel = new JPanel();

                ImageIcon icon = new ImageIcon();
                JLabel label = new JLabel(icon, JLabel.CENTER);

                ImageIcon buffericon = new ImageIcon("src/gif/loading.gif");
                Image img = buffericon.getImage();
                Image newimg = img.getScaledInstance(300, 250, Image.SCALE_DEFAULT);

                icon = new ImageIcon(newimg);
                label.setBounds(0, 0, 500, 500);

                label.setIcon(icon);

                panel.setLayout(null);
                panel.add(label);
                panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
                frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
                panel.setBackground(Color.white);
                frame.add(panel);
                frame.setUndecorated(true);
                frame.setSize(400, 400);
                frame.setVisible(true);
                frame.setBackground(new Color(0, 0, 0, 0));
                panel.setBackground(new Color(0, 0, 0, 0));
                label.setBackground(new Color(0, 0, 0, 0));
                frame.setLocation(750, 250);

                try {
                    Thread.sleep(2000);
                    frame.dispose();
                    dispose();
                    new Level_2().setVisible(true);
                    if (maxtime.isEmpty()) {
                        jLabel2_Moves.setText("0:0");
                    } else {

                    }

                } catch (Exception e) {
                }

                label.setSize(200, 200);
            });
            thread.start();
        }

    }

}
