/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GamesLevel;

import Score.MyText;
import Score.WriteAndRead_Level1;
import static Score.WriteAndRead_Level1.arrayList;
import Score.WriteAndRead_Level4;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Stack;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author Vipul
 */
public class Level_4 extends javax.swing.JFrame implements Runnable {

    private int boy_x;
    private int boy_y;
    private int Tresure1_X;
    private int Tresure2_X;
    private int Tresure3_X;

    private int Tresure1_Y;
    private int Tresure2_Y;
    private int Tresure3_Y;

    //Range Between Tresure and Boy
    private int Tresure1_boy_X;
    private int Tresure1_boy_Y;

    private int Tresure2_boy_X;
    private int Tresure2_boy_Y;

    private int Tresure3_boy_X;
    private int Tresure3_boy_Y;

    // boy data store
    private final ArrayList<Integer> x_array_boy = new ArrayList<>();
    private final ArrayList<Integer> y_array_boy = new ArrayList<>();

    private static final Stack<ArrayList> X_cordinateDB_boy = new Stack<>();
    private static final Stack<ArrayList> Y_cordinateDB_boy = new Stack<>();

    // Tresure1 data store
    private final ArrayList<Integer> x_array_tresure1 = new ArrayList<>();
    private final ArrayList<Integer> y_array_tresure1 = new ArrayList<>();

    private static final Stack<ArrayList> X_cordinateDB_tresure1 = new Stack<>();
    private static final Stack<ArrayList> Y_cordinateDB_tresure1 = new Stack<>();

    //Tresure2 data store
    private final ArrayList<Integer> x_array_tresure2 = new ArrayList<>();
    private final ArrayList<Integer> y_array_tresure2 = new ArrayList<>();

    private static final Stack<ArrayList> X_cordinateDB_tresure2 = new Stack<>();
    private static final Stack<ArrayList> Y_cordinateDB_tresure2 = new Stack<>();

    //Tresure3 data store
    private final ArrayList<Integer> x_array_tresure3 = new ArrayList<>();
    private final ArrayList<Integer> y_array_tresure3 = new ArrayList<>();

    private static final Stack<ArrayList> X_cordinateDB_tresure3 = new Stack<>();
    private static final Stack<ArrayList> Y_cordinateDB_tresure3 = new Stack<>();

    //other things
    private int boy_count = 0;
    private int tresure_count1 = 0;
    private int tresure_count2 = 0;
    private int tresure_count3 = 0;

    private int boy_x_undo;
    private int boy_y_undo;
    private int Tresure1_x_undo;
    private int Tresure1_y_undo;
    private int Tresure2_x_undo;
    private int Tresure2_y_undo;
    private int Tresure3_x_undo;
    private int Tresure3_y_undo;

    private static Clip clip;

    // Time
    private final int i = 0;
    private int startMinutes = 0;
    private final String maxtime;
    private String maxtime1;

    private int j = 0;

    /**
     * Creates new form Level_4
     */
    public Level_4() {
        initComponents();
        PlayMusic();
        time();
        setLocation(600, 100);
        Box_1.setVisible(false);
        Box_2.setVisible(false);
        Box_3.setVisible(false);
        if (new WriteAndRead_Level4().readObject() == null) {
            jLabel2_Moves.setText("");
            maxtime = "00:00";
        } else {

            jLabel2_Moves.setText(WriteAndRead_Level4.txt.toString());
            maxtime = WriteAndRead_Level4.txt.toString();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3_tresure3 = new javax.swing.JButton();
        jButton2_tresure2 = new javax.swing.JButton();
        jButton1_tresure1 = new javax.swing.JButton();
        jButton_boy = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Box_1 = new javax.swing.JButton();
        Box_2 = new javax.swing.JButton();
        Box_3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4_Time1 = new javax.swing.JLabel();
        jLabel4_Time = new javax.swing.JLabel();
        jLabel2_Moves = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1_sound = new javax.swing.JButton();
        jButton1_undo1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel6_X = new javax.swing.JLabel();
        jLabel5_Y = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8_x = new javax.swing.JLabel();
        jLabel9_y = new javax.swing.JLabel();

        jLabel2.setText("        1 ");
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jButton3_tresure3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon1_3.jpg"))); // NOI18N
        jButton3_tresure3.setText("3");
        jPanel1.add(jButton3_tresure3);
        jButton3_tresure3.setBounds(150, 470, 70, 60);

        jButton2_tresure2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon1_3.jpg"))); // NOI18N
        jButton2_tresure2.setText("2");
        jPanel1.add(jButton2_tresure2);
        jButton2_tresure2.setBounds(340, 470, 70, 60);

        jButton1_tresure1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon1_3.jpg"))); // NOI18N
        jButton1_tresure1.setText("1");
        jPanel1.add(jButton1_tresure1);
        jButton1_tresure1.setBounds(220, 400, 70, 60);

        jButton_boy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon1.png"))); // NOI18N
        jButton_boy.setText("BOY");
        jButton_boy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_boyKeyPressed(evt);
            }
        });
        jPanel1.add(jButton_boy);
        jButton_boy.setBounds(270, 150, 70, 60);

        jLabel5.setForeground(new java.awt.Color(204, 0, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2_2.png"))); // NOI18N
        jLabel5.setText("        3 ");
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 540, 70, 60);

        jLabel4.setForeground(new java.awt.Color(204, 0, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2_2.png"))); // NOI18N
        jLabel4.setText("        2 ");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 330, 70, 60);

        jLabel3.setForeground(new java.awt.Color(204, 0, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2_2.png"))); // NOI18N
        jLabel3.setText("        1 ");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 330, 70, 60);

        Box_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2_1.png"))); // NOI18N
        jPanel1.add(Box_1);
        Box_1.setBounds(0, 600, 70, 60);

        Box_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2_1.png"))); // NOI18N
        jPanel1.add(Box_2);
        Box_2.setBounds(0, 660, 70, 60);

        Box_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon2_1.png"))); // NOI18N
        jPanel1.add(Box_3);
        Box_3.setBounds(0, 720, 70, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maps/Level-4.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 569, 794);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 800));

        jLabel4_Time1.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jLabel4_Time1.setText(" Time");
        jLabel4_Time1.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel4_Time1.setPreferredSize(new java.awt.Dimension(59, 32));
        getContentPane().add(jLabel4_Time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 880, 80, 40));

        jLabel4_Time.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4_Time.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4_Time.setText("  Time");
        jLabel4_Time.setPreferredSize(new java.awt.Dimension(59, 32));
        getContentPane().add(jLabel4_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 880, 70, 40));

        jLabel2_Moves.setFont(new java.awt.Font("Digital-7 Mono", 1, 18)); // NOI18N
        jLabel2_Moves.setText("  Score");
        jLabel2_Moves.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel2_Moves, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 880, 80, 40));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("  Best Score");
        jLabel9.setPreferredSize(new java.awt.Dimension(59, 32));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 880, 100, 40));

        jButton1_sound.setText("Pause");
        jButton1_sound.setMaximumSize(new java.awt.Dimension(59, 32));
        jButton1_sound.setMinimumSize(new java.awt.Dimension(59, 32));
        jButton1_sound.setPreferredSize(new java.awt.Dimension(59, 32));
        jButton1_sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_soundActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_sound, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 880, 100, 40));

        jButton1_undo1.setText("Undo");
        jButton1_undo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_undo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_undo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 880, 110, 40));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("Target Location");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 800, 200, -1));

        jLabel6_X.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6_X.setText("   X");
        getContentPane().add(jLabel6_X, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 800, 80, -1));

        jLabel5_Y.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5_Y.setText("  Y");
        getContentPane().add(jLabel5_Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 800, 80, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("Tresure Location");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 840, 200, -1));

        jLabel8_x.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8_x.setText("   X");
        getContentPane().add(jLabel8_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 840, 80, -1));

        jLabel9_y.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9_y.setText("  Y");
        getContentPane().add(jLabel9_y, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 840, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_boyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_boyKeyPressed
        boy_x = jButton_boy.getLocation().x;
        boy_y = jButton_boy.getLocation().y;
        Tresure1_X = jButton1_tresure1.getLocation().x;
        Tresure2_X = jButton2_tresure2.getLocation().x;
        Tresure3_X = jButton3_tresure3.getLocation().x;

        Tresure1_Y = jButton1_tresure1.getLocation().y;
        Tresure2_Y = jButton2_tresure2.getLocation().y;
        Tresure3_Y = jButton3_tresure3.getLocation().y;

        goBoy(
                evt, boy_x, boy_y, Tresure1_X, Tresure2_X, Tresure3_X, Tresure1_Y,
                Tresure2_Y, Tresure3_Y
        );

        if (Tresure1_X == 140 && Tresure1_Y == 330) {
            tresure01(Tresure1_X, Tresure1_Y);
        }
        if (Tresure2_X == 340 && Tresure2_Y == 330) {
            tresure02(Tresure2_X, Tresure2_Y);
        }
        if (Tresure3_X == 150 && Tresure3_Y == 540) {
            tresure03(Tresure2_X, Tresure2_Y);
        }


    }//GEN-LAST:event_jButton_boyKeyPressed

    private void jButton1_undo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_undo1ActionPerformed
        undo_boy();
        undo_Tresure1();
        undo_Tresure2();
        undo_Tresure3();
    }//GEN-LAST:event_jButton1_undo1ActionPerformed

    private void jButton1_soundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_soundActionPerformed

        if (jButton1_sound.getText().equals("Play")) {

            PlayMusic();

            jButton1_sound.setText("Pause");
        } else {
            PauseMusic();
            jButton1_sound.setText("Play");

        }
    }//GEN-LAST:event_jButton1_soundActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Box_1;
    private javax.swing.JButton Box_2;
    private javax.swing.JButton Box_3;
    private javax.swing.JButton jButton1_sound;
    private javax.swing.JButton jButton1_tresure1;
    private javax.swing.JButton jButton1_undo1;
    private javax.swing.JButton jButton2_tresure2;
    private javax.swing.JButton jButton3_tresure3;
    private javax.swing.JButton jButton_boy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_Moves;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4_Time;
    private javax.swing.JLabel jLabel4_Time1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5_Y;
    private javax.swing.JLabel jLabel6_X;
    private javax.swing.JLabel jLabel8_x;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel9_y;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void goBoy(KeyEvent evt, int boy_x, int boy_y, int Tresure1_X, int Tresure2_X, int Tresure3_X, int Tresure1_Y, int Tresure2_Y, int Tresure3_Y) {
        this.boy_x = boy_x;
        this.boy_y = boy_y;
        this.Tresure1_X = Tresure1_X;
        this.Tresure2_X = Tresure2_X;
        this.Tresure3_X = Tresure3_X;
        this.Tresure1_Y = Tresure1_Y;
        this.Tresure2_Y = Tresure2_Y;
        this.Tresure3_Y = Tresure3_Y;

        Tresure1_boy_X = Tresure1_X - boy_x;
        Tresure1_boy_Y = Tresure1_Y - boy_y;

        Tresure2_boy_X = Tresure2_X - boy_x;
        Tresure2_boy_Y = Tresure2_Y - boy_y;

        Tresure3_boy_X = Tresure3_X - boy_x;
        Tresure3_boy_Y = Tresure3_Y - boy_y;

        int keys = evt.getKeyCode();

        switch (keys) {
            case KeyEvent.VK_UP:
                if ((boy_y == 70) || (boy_x <= 140 && boy_y == 200)
                        && (boy_x >= 70 && boy_y == 200)
                        || (boy_x == 420 && boy_y == 335)
                        || (boy_x == 335 && boy_y == 465)
                        || (boy_x == 340 && boy_y == 465)
                        || (boy_x == 240 && boy_y == 595)
                        || (boy_x == 245 && boy_y == 595)
                        || (boy_x == 140 && boy_y == 460)
                        || (boy_x == 145 && boy_y == 460)) {

                } else {
                    if (Tresure1_boy_X == 0 && Tresure1_boy_Y == -60) {
                        jLabel6_X.setText("" + 140);
                        jLabel5_Y.setText("" + 330);
                        if ((boy_y == 130) || (boy_x <= 145 && boy_y == 260)
                                && (boy_x >= 75 && boy_y == 260)
                                || (boy_x == 420 && boy_y == 395)
                                || (boy_x == 340 && boy_y == 525)
                                || (boy_x == 335 && boy_y == 520)
                                || (boy_x == 145 && boy_y == 520)
                                || (boy_x <= 245 && boy_y == 655)
                                && (boy_x >= 235 && boy_y == 655)) {

                        } else {
                            jButton_boy.setLocation(boy_x, boy_y - 5);
                            jButton1_tresure1.setLocation(Tresure1_X, Tresure1_Y - 5);
                            int X = jButton1_tresure1.getLocation().x;
                            int Y = jButton1_tresure1.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count1++;

                            x_array_tresure1.add(Tresure1_X);
                            X_cordinateDB_tresure1.push(x_array_tresure1);
                            y_array_tresure1.add(Tresure1_Y);
                            Y_cordinateDB_tresure1.push(y_array_tresure1);

                        }
                    }
                    if (Tresure2_boy_X == 0 && Tresure2_boy_Y == -60) {
                        jLabel6_X.setText("" + 340);
                        jLabel5_Y.setText("" + 330);
                        if ((boy_y == 130) || (boy_x <= 145 && boy_y == 260)
                                && (boy_x >= 75 && boy_y == 260)
                                || (boy_x == 420 && boy_y == 395)
                                || (boy_x == 340 && boy_y == 525)
                                || (boy_x == 335 && boy_y == 520)
                                || (boy_x == 145 && boy_y == 520)
                                || (boy_x <= 245 && boy_y == 655)
                                && (boy_x >= 235 && boy_y == 655)) {

                        } else {
                            jButton_boy.setLocation(boy_x, boy_y - 5);
                            jButton2_tresure2.setLocation(Tresure2_X, Tresure2_Y - 5);
                            int X = jButton2_tresure2.getLocation().x;
                            int Y = jButton2_tresure2.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count2++;

                            x_array_tresure2.add(Tresure2_X);
                            X_cordinateDB_tresure2.push(x_array_tresure2);
                            y_array_tresure2.add(Tresure2_Y);
                            Y_cordinateDB_tresure2.push(y_array_tresure2);
                        }
                    }
                    if (Tresure3_boy_X == 0 && Tresure3_boy_Y == -60) {
                        jLabel6_X.setText("" + 150);
                        jLabel5_Y.setText("" + 540);
                        if ((boy_y == 130) || (boy_x <= 145 && boy_y == 260)
                                && (boy_x >= 75 && boy_y == 260)
                                || (boy_x == 420 && boy_y == 395)
                                || (boy_x == 340 && boy_y == 525)
                                || (boy_x == 335 && boy_y == 520)
                                || (boy_x == 145 && boy_y == 520)
                                || (boy_x <= 245 && boy_y == 655)
                                && (boy_x >= 235 && boy_y == 655)) {

                        } else {
                            jButton_boy.setLocation(boy_x, boy_y - 5);
                            jButton3_tresure3.setLocation(Tresure3_X, Tresure3_Y - 5);
                            int X = jButton3_tresure3.getLocation().x;
                            int Y = jButton3_tresure3.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count3++;

                            x_array_tresure3.add(Tresure3_X);
                            X_cordinateDB_tresure3.push(x_array_tresure3);
                            y_array_tresure3.add(Tresure3_Y);
                            Y_cordinateDB_tresure3.push(y_array_tresure3);
                        }
                    } else {
                        jButton_boy.setLocation(boy_x, boy_y - 5);
                        boy_count++;
                        x_array_boy.add(boy_x);
                        X_cordinateDB_boy.push(x_array_boy);
                        y_array_boy.add(boy_y);
                        Y_cordinateDB_boy.push(y_array_boy);
                    }

                }
                break;
            case KeyEvent.VK_DOWN:

                if ((boy_y == 660) || (boy_x <= 425 && boy_y == 590)
                        && (boy_x >= 410 && boy_y == 590)
                        || (boy_x == 340 && boy_y == 335)
                        || (boy_x == 335 && boy_y == 335)
                        || (boy_x == 150 && boy_y == 335)
                        || (boy_x == 145 && boy_y == 335)
                        || (boy_x <= 245 && boy_y == 465)
                        && (boy_x >= 235 && boy_y == 465)
                        || (boy_x == 75 && boy_y == 465)
                        || (boy_x == 80 && boy_y == 465)) {

                } else {
                    if (Tresure1_boy_X == 0 && Tresure1_boy_Y == 60) {
                        jLabel6_X.setText("" + 140);
                        jLabel5_Y.setText("" + 330);
                        if ((boy_y == 600) || (boy_x == 75 && boy_y == 405)
                                || (boy_x <= 420 && boy_y == 530)
                                && (boy_x >= 405 && boy_y == 530)
                                || (boy_x <= 150 && boy_y == 275)
                                && (boy_x >= 140 && boy_y == 275)
                                || (boy_x >= 330 && boy_y == 275)
                                && (boy_x <= 340 && boy_y == 275)
                                || (boy_x <= 245 && boy_y == 405)
                                && (boy_x >= 235 && boy_y == 405)) {

                        } else {
                            jButton_boy.setLocation(boy_x, boy_y + 5);
                            jButton1_tresure1.setLocation(Tresure1_X, Tresure1_Y + 5);
                            int X = jButton1_tresure1.getLocation().x;
                            int Y = jButton1_tresure1.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count1++;

                            x_array_tresure1.add(Tresure1_X);
                            X_cordinateDB_tresure1.push(x_array_tresure1);
                            y_array_tresure1.add(Tresure1_Y);
                            Y_cordinateDB_tresure1.push(y_array_tresure1);
                        }
                    }
                    if (Tresure2_boy_X == 0 && Tresure2_boy_Y == 60) {
                        jLabel6_X.setText("" + 340);
                        jLabel5_Y.setText("" + 330);
                        if ((boy_y == 600) || (boy_x == 75 && boy_y == 405)
                                || (boy_x <= 420 && boy_y == 530)
                                && (boy_x >= 405 && boy_y == 530)
                                || (boy_x <= 150 && boy_y == 275)
                                && (boy_x >= 140 && boy_y == 275)
                                || (boy_x >= 330 && boy_y == 275)
                                && (boy_x <= 340 && boy_y == 275)
                                || (boy_x <= 245 && boy_y == 405)
                                && (boy_x >= 235 && boy_y == 405)) {

                        } else {
                            jButton_boy.setLocation(boy_x, boy_y + 5);
                            jButton2_tresure2.setLocation(Tresure2_X, Tresure2_Y + 5);
                            int X = jButton2_tresure2.getLocation().x;
                            int Y = jButton2_tresure2.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count2++;

                            x_array_tresure2.add(Tresure2_X);
                            X_cordinateDB_tresure2.push(x_array_tresure2);
                            y_array_tresure2.add(Tresure2_Y);
                            Y_cordinateDB_tresure2.push(y_array_tresure2);
                        }
                    }
                    if (Tresure3_boy_X == 0 && Tresure3_boy_Y == 60) {
                        jLabel6_X.setText("" + 150);
                        jLabel5_Y.setText("" + 540);
                        if ((boy_y == 600) || (boy_x == 75 && boy_y == 405)
                                || (boy_x <= 420 && boy_y == 530)
                                && (boy_x >= 405 && boy_y == 530)
                                || (boy_x <= 150 && boy_y == 275)
                                && (boy_x >= 140 && boy_y == 275)
                                || (boy_x >= 330 && boy_y == 275)
                                && (boy_x <= 340 && boy_y == 275)
                                || (boy_x <= 245 && boy_y == 405)
                                && (boy_x >= 235 && boy_y == 405)) {

                        } else {
                            jButton_boy.setLocation(boy_x, boy_y + 5);
                            jButton3_tresure3.setLocation(Tresure3_X, Tresure3_Y + 5);
                            int X = jButton3_tresure3.getLocation().x;
                            int Y = jButton3_tresure3.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count3++;

                            x_array_tresure3.add(Tresure3_X);
                            X_cordinateDB_tresure3.push(x_array_tresure3);
                            y_array_tresure3.add(Tresure3_Y);
                            Y_cordinateDB_tresure3.push(y_array_tresure3);
                        }
                    } else {
                        jButton_boy.setLocation(boy_x, boy_y + 5);
                        boy_count++;
                        x_array_boy.add(boy_x);
                        X_cordinateDB_boy.push(x_array_boy);
                        y_array_boy.add(boy_y);
                        Y_cordinateDB_boy.push(y_array_boy);
                    }

                }
                break;
            case KeyEvent.VK_LEFT:
                if ((boy_x == 205 && boy_y <= 135) && (boy_x == 205
                        && boy_y >= 70) || (boy_x == 75)
                        || (boy_x == 145 && boy_y >= 520)
                        && (boy_x == 145 && boy_y <= 665)
                        || (boy_x == 310 && boy_y <= 535)
                        && (boy_x == 310 && boy_y >= 525)
                        || (boy_x == 215 && boy_y == 400)
                        || (boy_x == 215 && boy_y == 395)
                        || (boy_x == 410 && boy_y <= 405)
                        && (boy_x == 410 && boy_y >= 395)) {

                } else {
                    if (Tresure1_boy_X == -70 && Tresure1_boy_Y == 0) {
                         jLabel6_X.setText("" + 140);
                        jLabel5_Y.setText("" + 330);
                        if ((boy_y == 295)
                                || (boy_x == 275 && boy_y <= 150)
                                && (boy_x == 275 && boy_y >= 70)
                                || (boy_x == 215 && boy_y >= 515)
                                && (boy_x == 215 && boy_y <= 660)
                                || (boy_x == 285 && boy_y <= 405)
                                && (boy_x == 285 && boy_y >= 395)
                                || (boy_x == 380 && boy_y <= 540)
                                && (boy_x == 380 && boy_y >= 525)
                                || (boy_x == 145 && boy_y >= 200)
                                && (boy_x == 145 && boy_y <= 465)) {

                        } else {
                            jButton_boy.setLocation(boy_x - 5, boy_y);
                            jButton1_tresure1.setLocation(Tresure1_X - 5, Tresure1_Y);
                            int X = jButton1_tresure1.getLocation().x;
                            int Y = jButton1_tresure1.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count1++;

                            x_array_tresure1.add(Tresure1_X);
                            X_cordinateDB_tresure1.push(x_array_tresure1);
                            y_array_tresure1.add(Tresure1_Y);
                            Y_cordinateDB_tresure1.push(y_array_tresure1);

                        }
                    }
                    if (Tresure2_boy_X == -70 && Tresure2_boy_Y == 0) {
                         jLabel6_X.setText("" + 340);
                        jLabel5_Y.setText("" + 330);
                        if ((boy_y == 295)
                                || (boy_x == 275 && boy_y <= 150)
                                && (boy_x == 275 && boy_y >= 70)
                                || (boy_x == 215 && boy_y >= 515)
                                && (boy_x == 215 && boy_y <= 660)
                                || (boy_x == 285 && boy_y <= 405)
                                && (boy_x == 285 && boy_y >= 395)
                                || (boy_x == 380 && boy_y <= 540)
                                && (boy_x == 380 && boy_y >= 525)
                                || (boy_x == 145 && boy_y >= 200)
                                && (boy_x == 145 && boy_y <= 465)) {

                        } else {
                            jButton_boy.setLocation(boy_x - 5, boy_y);
                            jButton2_tresure2.setLocation(Tresure2_X - 5, Tresure2_Y);
                            int X = jButton2_tresure2.getLocation().x;
                            int Y = jButton2_tresure2.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count2++;

                            x_array_tresure2.add(Tresure2_X);
                            X_cordinateDB_tresure2.push(x_array_tresure2);
                            y_array_tresure2.add(Tresure2_Y);
                            Y_cordinateDB_tresure2.push(y_array_tresure2);
                        }
                    }
                    if (Tresure3_boy_X == -70 && Tresure3_boy_Y == 0) {
                         jLabel6_X.setText("" + 150);
                        jLabel5_Y.setText("" + 540);
                        if ((boy_y == 295)
                                || (boy_x == 275 && boy_y <= 150)
                                && (boy_x == 275 && boy_y >= 70)
                                || (boy_x == 215 && boy_y >= 515)
                                && (boy_x == 215 && boy_y <= 660)
                                || (boy_x == 285 && boy_y <= 405)
                                && (boy_x == 285 && boy_y >= 395)
                                || (boy_x == 380 && boy_y <= 540)
                                && (boy_x == 380 && boy_y >= 525)
                                || (boy_x == 145 && boy_y >= 200)
                                && (boy_x == 145 && boy_y <= 465)) {

                        } else {
                            jButton_boy.setLocation(boy_x - 5, boy_y);
                            jButton3_tresure3.setLocation(Tresure3_X - 5, Tresure3_Y);
                            int X = jButton3_tresure3.getLocation().x;
                            int Y = jButton3_tresure3.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count3++;

                            x_array_tresure3.add(Tresure3_X);
                            X_cordinateDB_tresure3.push(x_array_tresure3);
                            y_array_tresure3.add(Tresure3_Y);
                            Y_cordinateDB_tresure3.push(y_array_tresure3);
                        }
                    } else {
                        jButton_boy.setLocation(boy_x - 5, boy_y);
                        boy_count++;
                        x_array_boy.add(boy_x);
                        X_cordinateDB_boy.push(x_array_boy);
                        y_array_boy.add(boy_y);
                        Y_cordinateDB_boy.push(y_array_boy);

                    }

                }
                break;
            case KeyEvent.VK_RIGHT:
                if ((boy_x == 420) || (boy_x == 350 && boy_y <= 275)
                        && (boy_x == 350 && boy_y >= 70)
                        || (boy_x == 350 && boy_y >= 645)
                        && (boy_x == 350 && boy_y <= 660)
                        || (boy_x == 170 && boy_y <= 540)
                        && (boy_x == 170 && boy_y >= 525)
                        || (boy_x == 75 && boy_y <= 405)
                        && (boy_x == 75 && boy_y >= 395)
                        || (boy_x == 265 && boy_y <= 410)
                        && (boy_x == 265 && boy_y >= 395)) {

                } else {
                    if (Tresure1_boy_X == 70 && Tresure1_boy_Y == 0) {
                         jLabel6_X.setText("" + 140);
                        jLabel5_Y.setText("" + 330);
                        if ((boy_x == 350 && boy_y == 415)
                                || (boy_x == 280 && boy_y <= 280)
                                && (boy_x == 280 && boy_y >= 70)
                                || (boy_x == 280 && boy_y <= 660)
                                && (boy_x == 280 && boy_y >= 640)
                                || (boy_x == 195 && boy_y >= 395)
                                && (boy_x == 195 && boy_y <= 405)
                                || (boy_x == 100 && boy_y <= 540)
                                && (boy_x == 100 && boy_y >= 525)
                                || (boy_x == 350 && boy_y >= 335)
                                && (boy_x == 350 && boy_y <= 590)) {

                        } else {
                            jButton_boy.setLocation(boy_x + 5, boy_y);
                            jButton1_tresure1.setLocation(Tresure1_X + 5, Tresure1_Y);
                            int X = jButton1_tresure1.getLocation().x;
                            int Y = jButton1_tresure1.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count1++;

                            x_array_tresure1.add(Tresure1_X);
                            X_cordinateDB_tresure1.push(x_array_tresure1);
                            y_array_tresure1.add(Tresure1_Y);
                            Y_cordinateDB_tresure1.push(y_array_tresure1);

                        }
                    }
                    if (Tresure2_boy_X == 70 && Tresure2_boy_Y == 0) {
                         jLabel6_X.setText("" + 340);
                        jLabel5_Y.setText("" + 330);
                        if ((boy_x == 350 && boy_y == 415)
                                || (boy_x == 280 && boy_y <= 280)
                                && (boy_x == 280 && boy_y >= 70)
                                || (boy_x == 280 && boy_y <= 660)
                                && (boy_x == 280 && boy_y >= 640)
                                || (boy_x == 195 && boy_y >= 395)
                                && (boy_x == 195 && boy_y <= 405)
                                || (boy_x == 100 && boy_y <= 540)
                                && (boy_x == 100 && boy_y >= 525)
                                || (boy_x == 350 && boy_y >= 335)
                                && (boy_x == 350 && boy_y <= 590)) {

                        } else {
                            jButton_boy.setLocation(boy_x + 5, boy_y);
                            jButton2_tresure2.setLocation(Tresure2_X + 5, Tresure2_Y);
                            int X = jButton2_tresure2.getLocation().x;
                            int Y = jButton2_tresure2.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count2++;

                            x_array_tresure2.add(Tresure2_X);
                            X_cordinateDB_tresure2.push(x_array_tresure2);
                            y_array_tresure2.add(Tresure2_Y);
                            Y_cordinateDB_tresure2.push(y_array_tresure2);
                        }
                    }
                    if (Tresure3_boy_X == 70 && Tresure3_boy_Y == 0) {
                         jLabel6_X.setText("" + 150);
                        jLabel5_Y.setText("" + 540);
                        if ((boy_x == 350 && boy_y == 415)
                                || (boy_x == 280 && boy_y <= 280)
                                && (boy_x == 280 && boy_y >= 70)
                                || (boy_x == 280 && boy_y <= 660)
                                && (boy_x == 280 && boy_y >= 640)
                                || (boy_x == 195 && boy_y >= 395)
                                && (boy_x == 195 && boy_y <= 405)
                                || (boy_x == 100 && boy_y <= 540)
                                && (boy_x == 100 && boy_y >= 525)
                                || (boy_x == 350 && boy_y >= 335)
                                && (boy_x == 350 && boy_y <= 590)) {

                        } else {
                            jButton_boy.setLocation(boy_x + 5, boy_y);
                            jButton3_tresure3.setLocation(Tresure3_X + 5, Tresure3_Y);
                            int X = jButton3_tresure3.getLocation().x;
                            int Y = jButton3_tresure3.getLocation().y;
                            jLabel8_x.setText("" + X);
                            jLabel9_y.setText("" + Y);
                            tresure_count3++;

                            x_array_tresure3.add(Tresure3_X);
                            X_cordinateDB_tresure3.push(x_array_tresure3);
                            y_array_tresure3.add(Tresure3_Y);
                            Y_cordinateDB_tresure3.push(y_array_tresure3);
                        }
                    } else {
                        jButton_boy.setLocation(boy_x + 5, boy_y);
                        boy_count++;
                        x_array_boy.add(boy_x);
                        X_cordinateDB_boy.push(x_array_boy);
                        y_array_boy.add(boy_y);
                        Y_cordinateDB_boy.push(y_array_boy);
                    }

                }
                break;

            default:
                System.out.println("Invalid");
        }
    }

    private void undo_boy() {

        if (boy_count > 0) {
            --boy_count;

            boy_x_undo = (int) X_cordinateDB_boy.pop().get(boy_count);
            boy_y_undo = (int) Y_cordinateDB_boy.pop().get(boy_count);

            jButton_boy.setLocation(boy_x_undo, boy_y_undo);

        }

    }

    private void tresure01(int x2, int y2) {

        if ((x2 == 140 && y2 == 330)) {

            jButton1_tresure1.setVisible(false);
            jLabel3.setVisible(false);
            Box_1.setVisible(true);

            j++;

        }
    }

    private void tresure02(int x2, int y2) {

        if ((x2 == 340 && y2 == 330)) {

            jButton2_tresure2.setVisible(false);
            jLabel4.setVisible(false);
            Box_2.setVisible(true);

            j++;

        }
    }

    private void tresure03(int x2, int y2) {

        if ((x2 == 150 && y2 == 540)) {

            jButton3_tresure3.setVisible(false);
            jLabel5.setVisible(false);
            Box_3.setVisible(true);

            j++;

        }
    }

    private void undo_Tresure1() {
        if (tresure_count1 > 0) {

            --tresure_count1;

            Tresure1_x_undo = (int) X_cordinateDB_tresure1.pop().get(tresure_count1);
            Tresure1_y_undo = (int) Y_cordinateDB_tresure1.pop().get(tresure_count1);

            jButton1_tresure1.setLocation(Tresure1_x_undo, Tresure1_y_undo);

        }
    }

    private void undo_Tresure2() {
        if (tresure_count2 > 0) {

            --tresure_count2;

            Tresure2_x_undo = (int) X_cordinateDB_tresure2.pop().get(tresure_count2);
            Tresure2_y_undo = (int) Y_cordinateDB_tresure2.pop().get(tresure_count2);

            jButton2_tresure2.setLocation(Tresure2_x_undo, Tresure2_y_undo);

        }
    }

    private void undo_Tresure3() {
        if (tresure_count3 > 0) {
            --tresure_count3;

            Tresure3_x_undo = (int) X_cordinateDB_tresure3.pop().get(tresure_count3);
            Tresure3_y_undo = (int) Y_cordinateDB_tresure3.pop().get(tresure_count3);

            jButton3_tresure3.setLocation(Tresure3_x_undo, Tresure3_y_undo);

        }
    }

    private void PlayMusic() {
        try {
            File file = new File("music1.wav");
            if (file.exists()) {

                try (AudioInputStream audio2 = AudioSystem.getAudioInputStream(file)) {

                    try {

                        clip = AudioSystem.getClip();
                        clip.open(audio2);
                        clip.start();
                        clip.loop(Clip.LOOP_CONTINUOUSLY);

                    } catch (LineUnavailableException | IOException ex) {

                    }

                }
            }

        } catch (IOException | UnsupportedAudioFileException e) {

        }

    }

    private String PauseMusic() {
        try {
            File file = new File("music1.wav");
            if (file.exists()) {

                long microsecondLength = clip.getMicrosecondLength();
                clip.stop();
                clip.setMicrosecondPosition(microsecondLength);

                clip.flush();
                clip.close();

            }
        } catch (Exception e) {

        }

        return "";

    }

    private void time() {

        Thread thread = new Thread(this);

        thread.start();

    }

    @Override
    public void run() {
        int second = 0;
        try {

            int time = 0;

            while (startMinutes < 8) {
                for (time = 0; time <= 60; time++) {
                    Thread.sleep(1000);
                    JLabel j = new JLabel();

                    j.setText("0" + startMinutes + ":" + i);
                    jLabel4_Time1.setText(j.getText());

                    if (i == 60) {
                        startMinutes++;
                        j.setText(startMinutes + ":" + i);
                    }
                }

            }

            second++;

        } catch (Exception e) {
        }
    }

    private void BufferImage() {
        if (i == 3) {
            maxtime1 = jLabel4_Time1.getText();
            if (WriteAndRead_Level1.arrayList.isEmpty()) {
                MyText date1 = new MyText();
                date1.setText(maxtime);
                MyText date2 = new MyText();
                date2.setText(maxtime1);
                arrayList.add(date1);
                new WriteAndRead_Level1().writeObject(maxtime1, maxtime);

            } else {
                MyText date1 = new MyText();
                date1.setText(maxtime);
                MyText date2 = new MyText();
                date2.setText(maxtime1);
                arrayList.add(date1);
                new WriteAndRead_Level1().writeObject(maxtime, maxtime1);
            }
            Thread thread = new Thread(() -> {
                JFrame frame = new JFrame();
                frame.getContentPane();
                JPanel panel = new JPanel();

                ImageIcon icon = new ImageIcon();
                JLabel label = new JLabel(icon, JLabel.CENTER);

                ImageIcon buffericon = new ImageIcon("src/gif/loading.gif");
                Image img = buffericon.getImage();
                Image newimg = img.getScaledInstance(300, 250, Image.SCALE_DEFAULT);

                icon = new ImageIcon(newimg);
                label.setBounds(0, 0, 500, 500);

                label.setIcon(icon);

                panel.setLayout(null);
                panel.add(label);
                panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
                frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
                panel.setBackground(Color.white);
                frame.add(panel);
                frame.setUndecorated(true);
                frame.setSize(400, 400);
                frame.setVisible(true);
                frame.setBackground(new Color(0, 0, 0, 0));
                panel.setBackground(new Color(0, 0, 0, 0));
                label.setBackground(new Color(0, 0, 0, 0));
                frame.setLocation(750, 250);

                try {
                    Thread.sleep(2000);
                    frame.dispose();
                    dispose();
                    new Level_5().setVisible(true);
                    if (maxtime.isEmpty()) {
                        jLabel2_Moves.setText("0:0");
                    } else {

                    }
                } catch (Exception e) {
                }

                label.setSize(200, 200);
            });
            thread.start();
        }

    }
}
